language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t thomasbtatum/frontend -f Dockerfile.dev .

script:
   - docker run -e CI=true thomasbtatum/frontend npm run test -- --coverage
